engines:
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
        - "java-braces"
        - "java-clone"
        - "java-codesize"
        - "java-comments"
        - "java-controversial"
        - "java-coupling"
        - "java-design"
        - "java-empty"
        - "java-finalizers"
        - "java-imports"
        - "java-junit"
        - "java-naming"
        - "java-optimizations"
        - "java-strictexception"
        - "java-strings"
        - "java-sunsecure"
        - "java-typeresolution"
        - "java-unnecessary"
        - "java-unusedcode"

ratings:
  paths:
  - "**.java"