language: java
jdk:
  - oraclejdk8
addons:
  sonarqube:
    token:
      secure: "QqGeNHOF1aPWE5wfXxKcs7s1fpSPC30ujUHDQHzI6uIdL2DWfiVfImWjqc9i92oNyw8r+pzxycYkgz0W0USdZouAvb/Kj6SEmyVwR0SGFS7EcDilwdSP2U1szlKJUZSNaA4eTFfkeRTrBVtNV7D8Rjj5W6jXkqNKoW5j4dSZvqf/L4n7uGG1T54u4vMTC8a175BZSN4X2MYG0OLIT0oy7gxBh2DUDLhx6P5KbaFnTpuZlaNGRxioibHpi2XK9yIw3XI20QYE4pHwV8dzIYERvbzUR8vL04FGMA6ujR9PRXiUQLTqIL70U70GUkL0KWqXYY2nLFW8jP2gdzE3yxDGoLU0ZfO59ca2EvoGc4RrmkQ3ahrKuYhEgc0lFKbASjZnBbRrfAxVqAsnBBrSLa+In8T+lgr6jmCb7TnftxvfxYIskzWSfRe+r/UbvNn1qEoHKBa9aFN8WJoaDxN7Gg12l9s/OM4HfhRGooHaOkxpohdoUW2k+MbqtXs2UMt2UouuyV1vCAmlQs8hd7BkjLFRNVjYFZm0SMLNjRNX3/K4gPj2q0SWGK5foAtP9JGTqiYp+O6uwEPVNpNgjGqENfWeLP2Y5Cog4HHeSudo7Wvq8bj0jnK/8HbhfM70kNPGSLsYsqVsl8qtu3H5ReDPua5wRZQ4OQHSimPGJuCl7kU17Wo="
    github_token:
      secure: 70c45aec45b92f28e14b9159a18a20c92e2dddae
script:
  - sonar-scanner
notifications:
  webhooks: 
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify?secret=9zUXU4U9qL9xzRy3C0frJPCe9mRPiGlO3cJMfJYoln45j32ANX
    on_success: change # default: always
    on_failure: always # default: always
