dist: trusty
language: java

jdk:
- openjdk8

services:
- postgresql

addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "teiler"
    token:
      secure: "xledcssKTPnvqfs8yGkwN8akCOsaBxzItnodqEHfo862aB3LPH6ZcHEHuYlqPqRYhCxUZOzmElUyhZhJxTLogIZ5lFNX5M8XDogeMF2PaFeOuNG94MNmfSBxBBjT597XjhV1PX5e35U020hOgKX44Xk/4mKQ3ESwSrkkVlfsbW0lZHBlLyZlFNjs12K2kJHzdsnAa0z57AtQqmyq8VHht9/LqOPGkPsXQkVXYKvkENGkoJZimDUZewXi0lBVsfqlr8r1G7vKnmAy4UE5AO09Ud18I+cc6N7VSj2XBtMQQWzhLiz5Ry5d5wD6Vk8A1rLmLdvq0+0kPcvBjLwsjuy9AVeJw8Pe2dhMuVirn0ruAc7w2+HhR3MvCKqWJPZ1NbmwrYOZglYvbuz2bDiVLSqAsDC8sp4YsYSe+X87diMAgeo6I1qGxIBZt2So7PQa1X7Tu6KbhWtoFEYtzbW6AROJIIPRWoI95PJ+pj02DoxXLeN2qjQo/G7+hGxKwMu1XLDjL9262LwMVrhjqBwHqlDBe7oXOFPSZQMUIWCMJCjrTEWzbvMVT6hGU5tjtoHs6zFF0a0rqrLFrdAzCFP7gOy0Gv8H+i8HLpJSRNkbxZqIYALSelQB3YRVcsnLttCCZtyjCECh+fR6Wh5vPfUoPLJfjs/5DfcG37yBPYQ0dB05Z10="
    github_token:
      secure: "HHFS20Ue/s229pp2JlYYxY35olE8y3bdHUQaZiYlC4wtOCZv1tkqDNUOO3ushX6MtDB5jKJhjLe68m+Nb4meOwR2rbdoNnzRnK/f7FEbGB4ksuA+Wh2GCWqd+c8UGWlAlwhLMoDFwnIQ3R91+wAvwiM3KzpYko1Tve0MCsEx5de6YA7nVRIzoJ0kf3xdGvS/Xa3og0bLVqiT8/gB1cTFaj25GkXke6Kpqc+tAC2Zwtml1a6cUVqbFLuJdhIc2E/qaEbu60qPvF+VubIzgIf1msaBz/ZSosTqCCFl60pgjrfE8t64WTaeJIXVLrj2Ooucs8Wweq1J5KhEYXX3MEI+RX3CWhysA9hUlcTC+D8ctr8PRGtDaqpo5GdBKJhoZ9PZrydAUmJKk176QXuOtNfFwQheEssipJRgFupS256/MLMkCbsq6DNhSmA9qSxai87trH58TnHl91PYiqcbBSTRtEilkpbT+eeGNVRVR7nQ2CbnTzlfnKDwcznMw89Zza/TPoG9OPb9sFDBU9yBTNKKBKB8ey0kz42IYYisORxdz266V3cgMehGaTGS3JBo2x9po7vtHakPQGSLUQCr9hvcQyNHHtsahnPiZIrt9XcVUhkr3y30CGDQlwZZwGPKAqVf6Lu3vToPCqhFgp3/84+CRy+23F2aG8rZQE+gCyWR2Lg="

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.sonar/cache/

before_install:
- chmod +x ./gradlew

before_script:
- psql -U postgres -c "CREATE USER tylr WITH PASSWORD 'dGolICMsoO'";
- psql -U postgres -f src/dist/sql/1_reset-database.sql
- psql -U postgres -f src/dist/sql/2_setup-database.sql
- psql -U postgres tylr -f src/dist/sql/10_runEverytime.sql
- psql -U postgres tylr -f src/test/resources/insert_test_data.sql

script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew integrationTest
- sonar-scanner

after_success: 
- ./gradlew jacocoTestReport
- ./gradlew build
