dist: trusty
language: java
jdk:
- oraclejdk8
- openjdk8
addons:
  sonarqube:
    token:
      secure: QqGeNHOF1aPWE5wfXxKcs7s1fpSPC30ujUHDQHzI6uIdL2DWfiVfImWjqc9i92oNyw8r+pzxycYkgz0W0USdZouAvb/Kj6SEmyVwR0SGFS7EcDilwdSP2U1szlKJUZSNaA4eTFfkeRTrBVtNV7D8Rjj5W6jXkqNKoW5j4dSZvqf/L4n7uGG1T54u4vMTC8a175BZSN4X2MYG0OLIT0oy7gxBh2DUDLhx6P5KbaFnTpuZlaNGRxioibHpi2XK9yIw3XI20QYE4pHwV8dzIYERvbzUR8vL04FGMA6ujR9PRXiUQLTqIL70U70GUkL0KWqXYY2nLFW8jP2gdzE3yxDGoLU0ZfO59ca2EvoGc4RrmkQ3ahrKuYhEgc0lFKbASjZnBbRrfAxVqAsnBBrSLa+In8T+lgr6jmCb7TnftxvfxYIskzWSfRe+r/UbvNn1qEoHKBa9aFN8WJoaDxN7Gg12l9s/OM4HfhRGooHaOkxpohdoUW2k+MbqtXs2UMt2UouuyV1vCAmlQs8hd7BkjLFRNVjYFZm0SMLNjRNX3/K4gPj2q0SWGK5foAtP9JGTqiYp+O6uwEPVNpNgjGqENfWeLP2Y5Cog4HHeSudo7Wvq8bj0jnK/8HbhfM70kNPGSLsYsqVsl8qtu3H5ReDPua5wRZQ4OQHSimPGJuCl7kU17Wo=
    github_token:
      secure: 70c45aec45b92f28e14b9159a18a20c92e2dddae
before_install:
- chmod +x ./gradlew
script:
- ./gradlew assemble
- ./gradlew check
- sonar-scanner
after_success: ./gradlew build
notifications:
  webhooks:
    urls:
    - https://fathomless-fjord-24024.herokuapp.com/notify?secret=9zUXU4U9qL9xzRy3C0frJPCe9mRPiGlO3cJMfJYoln45j32ANX
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: NaU5wgoLKPhnj5JsxIt3zBQ+c/t0Zb5Q4yLpjFm+La9gzYEtDv1x22dwqZTp7+FfOreZimQT1dRj0mwobyUVmZ0/bGWNtFoVbp2uGzkjwe8fpcm6NcZ0SRIJN0TufU0D5kZIMwTRQwRv+Z0mHsYq6lmCnvUpA/ZXFYHtcJGwLxhOgyiP8c9VsVQSt9kD9u6UGkjx2BOdK1sfqXw0ZQ2a+ljTdLog6k7Ib3MSNvkWmthsNCWB4KZCpXaYvIQ9ERhOlsgxlgwP9r3fPibPGcVwjz2+9oGYNtqb+Ck+IMgPdAgSHX5rBjOiUVgLNGpHaG2GWYcP4luLL64TsmBfKVtUJJvtLD2PeAVLXA47mw/TBuP1vYQ/OwEDFWxM+LhkDxCf7x2jWJ2vyDNc7a0Nqv2pGRQVmhmamNRqM066XcjrV01UXA9zVgdkYbYGsP0pqJRCRIxm96eWSCKqd8DmUvKF+iiJhS4LDEc/y853L5JKdiPSKyw9IwWG9ogVml6DtckPMsBLARatBAxHMom5nkoqmm9ZFB3L7VBoV+tJmtCGzFmqSHFwA4ajvzHKNxihoO9RjpmdD6m+gEbHGipJAqTnoOs2mO5Sw1j3rr79JId4HZRJO0Bn+WZCkjY7Rk9Z1ZYqPv6VpAkjlhyjV1j3wTtlyE45DGAzMm7UfkiiFaJp6G4=
  file: ./build/distributions/tylr-api.tar
  skip_cleanup: true
  on:
    branch: master
    tags: true
